language: java
jdk:
  - openjdk8
node_js: "7"
dist: xenial
before_install:
  - sudo apt-get update
  - sudo apt-get install python3
install:
  - sudo apt-get install graphviz
  - pip3 install hanziconv
  - npm install gitbook-cli -g
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
jobs:
  include:
    - stage: test
      install: skip
      script: ./gradlew check
    - stage: build_docs
      script:
      - cp -R docs docs-target
      - cp -r docs-target/zh_TR/* docs-target/zh_CN/
      - python3 .travis/generate-zh_CN.py -o docs-target/zh_CN -s docs-target/zh_TR
      - cd docs-target
      - npm install safe-buffer
      - cd ..
      - gitbook install docs-target
      - gitbook build docs-target
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: docs-target/_book
stages:
  - test
  - build_docs